permalink: /:categories/:year/:month/:day/:title

exclude: ["README.md", "Makefile"]
markdown: kramdown
highlighter: rouge


title: JSDC Core Team
description: jsdc is JavaScript developer Community / Conference
url: http://blog.jsdc.tw
domain: blog.jsdc.tw

headline:
  link: http://2016.jsdc.tw
  title: console.log(JSDC)
  description: This is JS way to developing.

authors:
  Simon Sun:
    name: 孫豪佑
    avatar: http://i.imgur.com/t5BJCas.jpg
    email: blackghost0118@gmail.com
    github: SimonSun1988
  kevinchen:
    name: 陳明正
    avatar: 
    email: kevinxyz77@gmail.com
    github: kevinchenxyz
  poying:
    name: 陳柏穎
    avatar: http://s.gravatar.com/avatar/de7c8319cc3164cfa8cefb703b0ccf94?s=80
    email: poying.me@gmail.com
    github: poying
    google: 108574328493530489590
  andreayang:
    name: Andrea Yang
    avatar: http://www.gravatar.com/avatar/12a7b319f1db27d075682ffabf60dcf6?s=80
    email: liebeand@gmail.com
  clonncd:
    name: Caesar Chi
    avatar: http://s.gravatar.com/avatar/d4b19c40066abd9558bd63aa88c1bffe?s=80
    email: clonncd@gmail.com
    github: clonncd
  smlsun:
    name: 謝宗穎
    avatar: http://s.gravatar.com/avatar/b1cdc474586380022434865434fb0554?s=80
    email: smlsun@gmail.com
    github: smlsunxie
    google: 114562460176368030377
  cyrilhong:
    name: Cyril Hong
    avatar: https://avatars0.githubusercontent.com/u/2579972?v=2&s=80
    email: cyrilhong@gmail.com
    github: cyrilhong
  stanney:
    name: Stanney Yen
    avatar: https://avatars3.githubusercontent.com/u/12631?v=2&s=460
    email:  freehourse2sh@gmail.com
    github: Stanney
  andrew:
    name: Andrew Chen
    avatar: http://s.gravatar.com/avatar/b3ce65c034dcb5139ab26af444484a03?s=80
    email: chenpoanandrew@gmail.com
    github: PolarBearAndrew
  itchina110:
    name: 周裕波
    avatar: http://img2.w3ctech.com/fe98883782822da7514ec04b6fc6cdda.jpg
    github: jsdc-core
  df1:
    name: Ellis Chang
    avatar: https://media.licdn.com/mpr/mpr/shrink_100_100/p/4/000/142/25d/34ec728.jpg
    github: df1
  ivanwei:
    name: Ivan Wei
    avatar: https://s.gravatar.com/avatar/b3417b9a40d628abdab1d9f1a9f71e79?s=80
    email: scorpionseed@gmail.com
    github: ivanwei
  jsdc:
    name: JSDC team
    avatar: http://cdn.inside.com.tw/wp-content/uploads/2012/04/website_logo.png
    email: hq@jsdc.tw
    github: jsdc-core

  ali:
    name: ALi
    avatar: https://avatars1.githubusercontent.com/u/5118200?v=3&s=460
    email: ali.li@jsdc.tw
    github: esbb48
  webber:
    name: Webber
    avatar: https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/12341135_1105783529441108_2938587828859091543_n.jpg?oh=cbfffb245f5d73a3b00d06f4cd854e4d&oe=5849E2E6
    github: webber0928

menu:
  - text: Home
    href: /
    page: home
  - text: About
    href: /#about
    page: about
  - text: JSDC
    href: http://2016.jsdc.tw
    page: jsdc2016
  - text: Design
    href: /2014/08/20/jsdc-design/
    page: design
  - text: Angular.tw
    href: http://www.fb.com/groups/augularjs.tw/
    page: ng-tw
  - text: Front-End
    href: http://www.fb.com/groups/f2e.tw/
    page: front-end
  - text: HTML5
    href: http://www.fb.com/groups/htmlfive/
    page: html5
  - text: JS.tw
    href: http://www.fb.com/groups/javascript.tw/
    page: js-tw
  - text: Node.js
    href: http://fb.com/groups/node.js.tw/
    page: nodejs
